### ISSUE TITLE
Websocket introspect support

### ISSUE THREAD

**Issue by rashi-jaiswal-007** [revomatico/kong-oidc#18]
Websocket protocol does not allow to add headers like `Authorization`. Can we support checking for access_token even in query params? Something on below lines:
```
function M.has_bearer_access_token()
  local header = ngx.req.get_headers()['Authorization']
  if header and header:find(" ") then
    local divider = header:find(' ')
    if string.lower(header:sub(0, divider-1)) == string.lower("Bearer") then
      return true
    end
  end
  local args = ngx.req.get_uri_args()
  for key, val in pairs(args) do
    if key == "access_token" then
      local token = formatAsBearerToken(val)
      ngx.req.set_header('Authorization', token) // "resty.openidc".introspect - also does not allow query param usage
      return true
    end
  end
  return false
end
```

**Comment by ruiengana** [comment]
Websocket doesn’t have support for native Authorisation, therefore this is
implemented by the Developer on top of the Websocket protocol. Most of
 Websocket libraries add this layer already.

In my opinion this is concern of the micro itself and not the API Gateway,
which over Websocket acts purely as proxy.

**Comment by rashi-jaiswal-007** [comment]
> Most of Websocket libraries add this layer already

You mean something like [auth](https://socket.io/docs/v3/client-initialization/#auth) or [extraHeaders](https://socket.io/docs/v3/client-initialization/#extraHeaders) of socket.io? If yes, then are you suggesting that socket server should instead be responsible for introspecting the token passed via these (and kong-oidc plugin should be bypassed essentially) ?

**Comment by ruiengana** [comment]
Yes. You shouldn’t be applying REST fundamentals with Websockets. They are
utterly different. Only thing they actually share is the HTTP as the
transport layer.

REST is about avoid sessions by leveraging authorisation in stateless
calls. With websocket you actually create a duplex session via the
websocket.

**Comment by rashi-jaiswal-007** [comment]
Cool... sounds good
