### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by EndarValuk** [revomatico/kong-oidc#21]
According to https://github.com/Kong/kong/commit/0291c3c590d0e328e0633aa091b322f97add0e3d constant `CREDENTIAL_USERNAME` was removed.

That causes error while using `revomatico/docker-kong-oidc:latest` docker image

`
2022/09/29 11:48:25 [error] 1370#0: *593 [kong] init.lua:290 [oidc] /usr/local/share/lua/5.1/kong/plugins/oidc/utils.lua:122: header must be a string, client: 172.18.0.1, server: kong, request: "POST /data HTTP/1.1", host: "127.0.0.1:5100"
`

Repo was updated https://github.com/revomatico/kong-oidc/commit/431df6b6f344500a55c496ccb518a9f9c8fed6aa
But published version is 1.3.0-2, not 1.3.0-3

**Comment by zerodefect** [comment]
@revomatico, can you share the Dockerfile that is used to build the container? Thanks.

**Comment by zerodefect** [comment]
For anybody else with the same question, there is a repo located here: https://github.com/revomatico/docker-kong-oidc

**Comment by zerodefect** [comment]
@cristichiru are you able to help with updating the docker image in the Docker Hub?

**Comment by cr1cr1** [comment]
I do not understand, update with... what exactly? As far as I see `docker-kong-oidc` tag `3.0.0-6`:

https://github.com/revomatico/docker-kong-oidc/blob/71cd6d9dae19e89cec777151fc76f47fce09664a/Dockerfile#L9

uses the latest version with the fixes contributed by https://github.com/revomatico/kong-oidc/commits?author=diep-it-dn that were merged and released as tag `1.3.0-3`

**Comment by cr1cr1** [comment]
Ah, the docker hub image is not up to date!

Fixed: https://hub.docker.com/r/revomatico/docker-kong-oidc/tags?page=1&ordering=last_updated

As a general rule, please do not use `latest` tag except for testing. For production use an actual version, to have control over changes happening in time.

**Comment by zerodefect** [comment]
Understood. Thanks for investigating, Cristian.
